name: Actualizar Lista IPTV
on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar validador
        run: python validador.py
      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista_maestra.m3u
          git commit -m "Lista actualizada" || exit 0
          git push
